#' @title Simulated Sequence Data from a Variable Length Markov Chain (VLMC)
#' @name abc_data
#'
#' @description
#' The data objects `abc_vec` and `abc_list` contain sequences generated using a Variable Length Markov Chain (VLMC) with a specified context tree and transition probabilities.
#'
#' @format
#' - `abc_vec`: A character vector of length 1000 representing a single sequence generated by the VLMC.
#' - `abc_list`: A list of three character vectors, each of length 1000, representing independent sequences generated by the VLMC.
#'
#' @details
#' The VLMC used to generate the data was based on an alphabet of three symbols (`a`, `b`, and `c`) with a context tree constructed to a maximal depth of 3. The active contexts and their corresponding transition probabilities are as follows:
#'
#' - `*.a` (global context): `c(0.10, 0.20, 0.70)`
#' - `*.b`: `c(0.33, 0.33, 0.34)`
#' - `*.c.a`: `c(0.20, 0.10, 0.70)`
#' - `*.c.b`: `c(0.01, 0.98, 0.01)`
#' - `*.c.c`: `c(0.40, 0.40, 0.20)`
#'
#' The sequences were generated using a seed value of `1` to ensure reproducibility.
#'
#' @examples
#' # Access the single sequence
#' data(abc_vec)
#' print(abc_vec)
#'
#' # Access the list of sequences
#' data(abc_list)
#' print(abc_list)
#'
#' @source The data was generated using the `rvlmc` function in the R package \pkg{bacontrees}.
"abc_list"

#' @rdname abc_data
"abc_vec"
