# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compress_logical_cpp <- function(logical_vec, chunk_size) {
    .Call(`_bacontrees_compress_logical_cpp`, logical_vec, chunk_size)
}

check_active <- function(nodes) {
    .Call(`_bacontrees_check_active`, nodes)
}

